# .github/workflows/docker-publish.yml
name: Docker Build and Push

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest major version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Use the latest major version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Use the latest major version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Use the latest major version
        with:
          context: . # Use the root directory as context
          file: ./Dockerfile # Path to Dockerfile
          push: true # Push the image after building
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-image-slim:latest, ${{ secrets.DOCKERHUB_USERNAME }}/devops-image-slim:${{ github.sha }} # Tag with latest and the Git commit SHA